proxy:
  name: "MCP Memory Proxy Server"
  version: "1.0.0"
  host: "127.0.0.1"
  port: 8080
  debug: false
  
  # Auto-trigger settings
  auto_trigger:
    enabled: true
    auto_execute: true
    timeout_seconds: 30
    max_retries: 3
    
  # Production mode configuration
  testing:
    enabled: false  # Production mode: forward to real platforms
    return_analysis_metadata: false
  
  # Platform configurations
  platforms:
    cursor:
      name: "Cursor AI Platform"
      enabled: true
      base_url: "https://api.cursor.sh/v1"  # Real Cursor API endpoint
      timeout: 30
      headers:
        Content-Type: "application/json"
        User-Agent: "MCP-Memory-Proxy/1.0"
      
    claude:
      name: "Claude AI Platform" 
      enabled: false
      base_url: "https://api.anthropic.com/v1"
      timeout: 30
      headers:
        Content-Type: "application/json"
        User-Agent: "MCP-Memory-Proxy/1.0"
        
    universal:
      name: "Universal AI Platform"
      enabled: false
      timeout: 30
      headers:
        Content-Type: "application/json"
        User-Agent: "MCP-Memory-Proxy/1.0"
  
  # Caching settings
  cache:
    enabled: true
    ttl_seconds: 300
    max_size: 1000
  
  # Performance settings
  performance:
    max_concurrent_requests: 10
    request_timeout: 30
    max_memory_contexts: 5
