name: ci-minimal

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-lint-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install fastapi uvicorn pytest ruff
      - name: Lint
        run: ruff check .
      - name: Unit tests
        run: pytest -q
      - name: Build Docker
        run: docker build -t mcp-memory-server:ci .
